### ISSUE TITLE
Need Help with Jacoco

### ISSUE THREAD

**Issue by Jacopo-Inglese** [SerafinoDiGiambattista/ProgettoSW#20]
Serafino il coverage non raggiunge la soglia sperata.
Potresti aiutarmi a coprire i le classi di test del tool in Java dividendoci il lavoro?
Dovresti cercare di creare degli oggetti Matrice o Document che riescano a essere usati nel testing

**Comment by SerafinoDiGiambattista** [comment]
Alla fine sono riuscito a creare dei test raggiungendo la soglia superata
